// Sample data for the llml profile catalog UI kit.
window.PROFILES = [
  {
    id: "qwen3-14b-coding-cuda",
    name: "Qwen3 14B Coding Profile",
    fit: "Optimized for 24GB NVIDIA cards with KoboldCpp and longer context.",
    backend: "koboldcpp",
    hardware: "24GB NVIDIA",
    os: "Linux",
    useCase: "Coding",
    verified: true,
    updated: "3 days ago",
    maintainer: "@flyingnobita",
    repoPath: "profiles/qwen3-14b-coding.toml",
    commit: "8a4f1c2",
    importCmd: "llml import qwen3-14b-coding.toml",
    rationale:
      "Built around the Qwen3 14B Instruct GGUF (Q4_K_M). The defaults balance long context for repo-wide reasoning against the 24GB VRAM ceiling, leaving headroom for KV cache without offloading layers to CPU.",
    args: [
      "--gpulayers 80",
      "--contextsize 16384",
      "--threads 8",
      "--flashattention",
    ],
    env: [{ key: "CUDA_VISIBLE_DEVICES", value: "0" }],
    related: ["llama-33-70b-2x24gb", "qwen3-14b-cpu-fallback"],
  },
  {
    id: "llama-33-70b-2x24gb",
    name: "Llama 3.3 70B — 2× 24GB CUDA",
    fit: "Two-card NVIDIA box, vLLM tensor-parallel, balanced throughput + interactive.",
    backend: "vllm",
    hardware: "2× 24GB NVIDIA",
    os: "Linux",
    useCase: "Chat",
    verified: true,
    updated: "1 week ago",
    maintainer: "@bench-lab",
    repoPath: "profiles/llama-33-70b-2x24gb.toml",
    commit: "f1c8e0a",
    importCmd: "llml import llama-33-70b-2x24gb.toml",
    rationale:
      "Tensor-parallel across 2× 24GB cards (3090 / 4090 class). AWQ quantization keeps the model resident with room for 32k context.",
    args: [
      "--tensor-parallel-size 2",
      "--gpu-memory-utilization 0.92",
      "--max-model-len 32768",
    ],
    env: [],
    related: ["qwen3-14b-coding-cuda"],
  },
  {
    id: "gemma-3-12b-mac",
    name: "Gemma 3 12B — Apple Silicon Balanced",
    fit: "Built for Apple Silicon laptop use with tighter memory constraints.",
    backend: "llama.cpp",
    hardware: "Apple Silicon · 32GB",
    os: "macOS",
    useCase: "Chat",
    verified: false,
    updated: "2 weeks ago",
    maintainer: "@morrowind",
    repoPath: "profiles/gemma-3-12b-mac.toml",
    commit: "2b0d743",
    importCmd: "llml import gemma-3-12b-mac.toml",
    rationale:
      "M2/M3/M4 Pro with 32GB unified memory. Metal backend, conservative KV cache so the laptop stays usable while the model is hot.",
    args: ["--n-gpu-layers 99", "--ctx-size 8192", "--threads 6"],
    env: [],
    related: ["qwen3-14b-coding-cuda"],
  },
  {
    id: "phi-4-cpu-low-mem",
    name: "Phi-4 14B — CPU only, low memory",
    fit: "Workstation without a discrete GPU. Slower but fits in 16GB RAM.",
    backend: "llama.cpp",
    hardware: "CPU only",
    os: "Linux",
    useCase: "Completion",
    verified: false,
    updated: "1 month ago",
    maintainer: "@cpu-warrior",
    repoPath: "profiles/phi-4-cpu-low-mem.toml",
    commit: "55a91b3",
    importCmd: "llml import phi-4-cpu-low-mem.toml",
    rationale:
      "Q4_K_M, 4 threads, no GPU offload. Intended for office laptops and CI runners where a dGPU isn't available.",
    args: ["--n-gpu-layers 0", "--ctx-size 4096", "--threads 4"],
    env: [],
    related: [],
  },
  {
    id: "ollama-llama32-default",
    name: "Llama 3.2 3B — Ollama default",
    fit: "Drop-in for the shared Ollama daemon. Keep-alive on, all layers on GPU.",
    backend: "ollama",
    hardware: "GPU · any",
    os: "Cross-platform",
    useCase: "Chat",
    verified: true,
    updated: "5 days ago",
    maintainer: "@ollama-friends",
    repoPath: "profiles/ollama-llama32-default.toml",
    commit: "a90b1c4",
    importCmd: "llml import ollama-llama32-default.toml",
    rationale:
      "Sets OLLAMA_NUM_GPU=999 and OLLAMA_NUM_CTX=8192. Works against a shared Ollama host without a per-model port.",
    args: [],
    env: [
      { key: "OLLAMA_NUM_GPU", value: "999" },
      { key: "OLLAMA_NUM_CTX", value: "8192" },
    ],
    related: [],
  },
  {
    id: "kobold-vulkan-amd",
    name: "Llama 3 8B — KoboldCpp Vulkan (AMD)",
    fit: "AMD GPU with Vulkan backend; CUDA not required.",
    backend: "koboldcpp",
    hardware: "AMD GPU",
    os: "Linux · Windows",
    useCase: "Chat",
    verified: false,
    updated: "3 weeks ago",
    maintainer: "@radeon-rider",
    repoPath: "profiles/kobold-vulkan-amd.toml",
    commit: "7df2901",
    importCmd: "llml import kobold-vulkan-amd.toml",
    rationale:
      "Vulkan path for AMD/Radeon hardware. 4k context, all layers on GPU.",
    args: ["--gpulayers 80", "--contextsize 4096", "--usevulkan"],
    env: [],
    related: [],
  },
];

window.FILTERS = {
  backend: ["llama.cpp", "vllm", "ollama", "koboldcpp"],
  hardware: ["24GB NVIDIA", "2× 24GB NVIDIA", "Apple Silicon", "AMD GPU", "CPU only"],
  os: ["Linux", "macOS", "Windows", "Cross-platform"],
  useCase: ["Chat", "Coding", "Completion", "Tool calling", "Embedding", "Batch"],
  source: ["Verified", "Community"],
};
