schema_version = 2

[[profiles]]
name = "Qwen3.6-35B-A3B-preserve-thinking"
backend = "llama"
model_hint = "qwen3.6"
args = [ "./llama.cpp/llama-server", "--alias unsloth/Qwen3.6-35B-A3B-GGUF", "--temp 0.6", "--top-p 0.95", "--top-k 20", "--min-p 0.00", "--port 8001", "--chat-template-kwargs {\"preserve_thinking\":true}" ]
model_org = "unsloth"
profile_org = "unsloth"

[profiles.use_case]
primary = "chat"
tags = [ "thinking" ]
