schema_version = 2

[[profiles]]
name = "Qwen3.6-disable-thinking-Windows"
backend = "llama"
model_hint = "Qwen3.6"
args = [ "--chat-template-kwargs \"{\\\"enable_thinking\\\":false}\"" ]
model_org = "unsloth"
profile_org = "unsloth"

[profiles.use_case]
primary = "chat"
tags = [ "non-thinking" ]
